language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "12"
deploy:
  skip_cleanup: true
  on:
    repo: iamolegga/express-ctx
    branch: master
  provider: npm
  email: iamolegga@gmail.com
  api_key:
    secure: XwIBQvTc+g9rkNEimm+ytv50gUUfSmbiNOYonYTJc+mSAp3UGFsaGSifAC5khFqOOi81u/7+QB2X53uv4zXZKBjw2BqpLJnaKT/cmXZNUtMGlcj99bn24NOD0DhXhw1hW+X/sVAIVhjNBBgjfooVq8MbHW4WXN1/VFenIOW7GnJgI1fS4nVkOS7xKNFcNb7VGQs4eVmDfrr1SKdRV3dcvtPeAfbe6bBGLB6PfXGFNOmZBFnXMvWsg9W+z1qvFi208Z12AHz2SLWZCP8Hf7JK3r730gO9cwwGx/Z4/EnZtUg4dbF5bdehjDPdYGbaorSekH8xn7S9P+UhOWNWKz4MiBEUcLpdZxqcDrPIfLQi0i8b9gs+gj6YaPR1VbBkTUyEh7EdWwjJxV4zzDA0cvbLRXXFSf9m8tkNleU/wk/YOFriV35HA+fNkoV3CZ9J6l3qGTXatJ3xQ8p0NWfXbC7OzCZUi4vBcQci6AD/oBwEOV9m1WjiivEwVaeAGpjewzV2nkttmsjL+nLBz9ua5mUG8NE/JBgqHTHbL0Uy4t0SPt0zteDLjn9MKtiYQ58eJoj6t+AH/7SGnFKTcUHUSa7kQbMDnm4qaJzl2BwWk34oZs5dc0fCKMdrZVdIWaJdzoN8v9dZxqMFpI0giIO2RVZO0WHbechVfKGy1gxbK6n9ID0=
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
